apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-peso-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-peso
  template:
    metadata:
      labels:
        app: conversao-peso
    spec:
      containers:
        - name: conversao-peso
          image: alyssonmartin142/conversao-peso:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-peso
spec:
  selector:
    app: conversao-peso
  ports:
    - port: 8080
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort
